# Generated by Django 5.0.6 on 2024-10-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bloodinventorymodel_bloodrequestmodel_donormodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequestmodel',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
